---
title: "Guía Ciudadana"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Motivación

This exercise was designed as part of an ongoing collaboration between INCAE Business School and Contraloría General de la República de Costa Rica.  It presents to the student with a concrete data challenge:  As a result of an open government policy, the Costa Rican Republic has made its procurement data publicly available.  The student is presented with some context information, a brief introduction to a basic framework on public value creation, a set of questions to help as a guide to understand the underlying technical infrastructure allowing this ability, and finally with a subset of data (over a hundred lines) of public data.   The dataset contains five years of information on information technology that was acquired or rented using public funds.  The challenge is to propose to public officials concrete ways to add value based on their analysis of these data.



>>>>>>> bf521825f6f39e3410dcf70efe9584354011d730

